server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: helloimkwang2
  app:
    services:
      auth: "http://localhost:8080/identity"